/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JOptionPane;
import proyectomelanie.baseDatos;



/**
 *
 * 
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    
    
    public Inicio() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_Usuario = new javax.swing.JLabel();
        lbl_Bienvenido = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbl_Contraseña = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_Usuario = new javax.swing.JTextField();
        btn_Continuar = new javax.swing.JButton();
        btn_Registrarse = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txt_Contraseña = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_Usuario.setFont(new java.awt.Font("Tekton Pro Ext", 3, 14)); // NOI18N
        lbl_Usuario.setForeground(new java.awt.Color(51, 51, 0));
        lbl_Usuario.setText("Usuario:");
        getContentPane().add(lbl_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 70, 20));

        lbl_Bienvenido.setBackground(new java.awt.Color(255, 102, 102));
        lbl_Bienvenido.setFont(new java.awt.Font("Vivaldi", 2, 48)); // NOI18N
        lbl_Bienvenido.setForeground(new java.awt.Color(102, 0, 0));
        lbl_Bienvenido.setText("Bienvenido");
        getContentPane().add(lbl_Bienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 220, 70));

        jLabel5.setFont(new java.awt.Font("Tekton Pro Cond", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 0, 51));
        jLabel5.setText("Et Lux in Tenebris Lucet");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 160, 30));

        lbl_Contraseña.setFont(new java.awt.Font("Tekton Pro Ext", 2, 14)); // NOI18N
        lbl_Contraseña.setText("Contraseña:");
        getContentPane().add(lbl_Contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, -1, -1));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 70)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 102));
        jLabel3.setText("PCUP");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 200, 90));

        txt_Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_UsuarioActionPerformed(evt);
            }
        });
        txt_Usuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_UsuarioKeyTyped(evt);
            }
        });
        getContentPane().add(txt_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 146, -1));

        btn_Continuar.setBackground(new java.awt.Color(0, 51, 51));
        btn_Continuar.setFont(new java.awt.Font("Tekton Pro Cond", 3, 24)); // NOI18N
        btn_Continuar.setForeground(new java.awt.Color(0, 51, 51));
        btn_Continuar.setText("Continuar");
        btn_Continuar.setFocusPainted(false);
        btn_Continuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ContinuarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Continuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 140, 40));

        btn_Registrarse.setBackground(new java.awt.Color(102, 0, 0));
        btn_Registrarse.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 2, 14)); // NOI18N
        btn_Registrarse.setForeground(new java.awt.Color(102, 102, 0));
        btn_Registrarse.setText("Registrarse");
        btn_Registrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RegistrarseActionPerformed(evt);
            }
        });
        btn_Registrarse.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btn_RegistrarseKeyTyped(evt);
            }
        });
        getContentPane().add(btn_Registrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 140, 20));

        jLabel1.setText("Si no tienes cuenta, haz clic en registrarse");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 220, -1));

        txt_Contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ContraseñaActionPerformed(evt);
            }
        });
        txt_Contraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_ContraseñaKeyTyped(evt);
            }
        });
        getContentPane().add(txt_Contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 150, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/users_21399.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 40, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/61_85304.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 30, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/next_user_16690.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 70, 60));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/research_books_22128 (1).png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 130, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/trophy_icon-icons.com_67206.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, 120));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/3.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
   
    
    private void btn_ContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ContinuarActionPerformed
            boolean Encontrado=false;
            String Alumno;
            String[] AlumnoArray;
            baseDatos BaseDatos=new baseDatos();
            
            
            
            if(txt_Usuario.getText().isEmpty()&& txt_Contraseña.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"Complete sus datos!");
                txt_Usuario.getText();
                txt_Contraseña.getText();
           
            }
            else if(txt_Usuario.getText().isEmpty()||txt_Contraseña.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"Complete sus datos!");
                txt_Usuario.getText();
                txt_Contraseña.getText();
            }
            else{
                    InscripcionCursos Matrícula= new InscripcionCursos();           
                    Matrícula.setVisible(true);
                    dispose();
                
            }
            
        
        
        
    }//GEN-LAST:event_btn_ContinuarActionPerformed

    private void txt_UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_UsuarioActionPerformed
      
        
        
    }//GEN-LAST:event_txt_UsuarioActionPerformed

    private void txt_UsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_UsuarioKeyTyped
        
        char _ch=evt.getKeyChar();
        if(!Character.isLetterOrDigit(_ch))evt.consume();
    }//GEN-LAST:event_txt_UsuarioKeyTyped

    private void btn_RegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RegistrarseActionPerformed
        
        Registrarse Interfaz=new Registrarse();
        Interfaz.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_RegistrarseActionPerformed

    private void btn_RegistrarseKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_RegistrarseKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_RegistrarseKeyTyped

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void txt_ContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ContraseñaActionPerformed
 
    }//GEN-LAST:event_txt_ContraseñaActionPerformed

    private void txt_ContraseñaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ContraseñaKeyTyped
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_txt_ContraseñaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Continuar;
    private javax.swing.JButton btn_Registrarse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbl_Bienvenido;
    private javax.swing.JLabel lbl_Contraseña;
    private javax.swing.JLabel lbl_Usuario;
    private javax.swing.JPasswordField txt_Contraseña;
    private javax.swing.JTextField txt_Usuario;
    // End of variables declaration//GEN-END:variables
}
