/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import Vista.Inicio;
import java.util.ArrayList;
import javax.swing.JOptionPane;
/**
 *
 * @author Lenovo
 */
public class InscripcionCursos extends javax.swing.JFrame {

    /**
     * Creates new form InscripcionCursos
     */
     private ArrayList<String>cursosSistemas=new ArrayList<>();
     private ArrayList<String>cursosMedicina=new ArrayList<>();

    public ArrayList<String> getCursosSistemas() {
        return cursosSistemas;
    }

    public void setCursosSistemas(ArrayList<String> cursosSistemas) {
        this.cursosSistemas = cursosSistemas;
    }

    
    

    public ArrayList<String> getCursosMedicina() {
        return cursosMedicina;
    }

    public void setCursosMedicina(ArrayList<String> cursosMedicina) {
        this.cursosMedicina = cursosMedicina;
    }

    
   
    
    public InscripcionCursos() {
        initComponents();
        this.setLocationRelativeTo(null);//centrar pestaña
        
        /*if(cmb_facultad.getSelectedIndex()==0){
            
        }
        cursosSistemas.add("Cálculo");
        cursosSistemas.add("Algoritmos");
        cursosSistemas.add("Computación Básica");
        cursosSistemas.add("Lenguaje");
        cursosSistemas.add("Arte");
        
        rbtn_Curso1.setText(cursosSistemas.get(0));
        rbtn_Curso2.setText(cursosSistemas.get(1));
        rbtn_Curso3.setText(cursosSistemas.get(2));
        rbtn_Curso4.setText(cursosSistemas.get(3));
        rbtn_Curso5.setText(cursosSistemas.get(4));
       
        txt_Curso1.setText("4.0");
        txt_Curso2.setText("4.0");
        txt_Curso3.setText("2.0");
        txt_Curso4.setText("3.0");
        txt_Curso5.setText("2.0");
        
        //*******************************
        
        cursosMedicina.add("Comunicación");
        cursosMedicina.add("Matemática");
        cursosMedicina.add("Ciencias Naturales");
        cursosMedicina.add("Biología");
        cursosMedicina.add("Filosofía");
        
        rbtn_Curso1.setText(cursosMedicina.get(0));
        rbtn_Curso2.setText(cursosMedicina.get(1));
        rbtn_Curso3.setText(cursosMedicina.get(2));
        rbtn_Curso4.setText(cursosMedicina.get(3));
        rbtn_Curso5.setText(cursosMedicina.get(4));
       
        txt_Curso1.setText("3.0");
        txt_Curso2.setText("5.0");
        txt_Curso3.setText("5.0");
        txt_Curso4.setText("3.0");
        txt_Curso5.setText("3.0");*/
      
    }
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        rbtn_Curso1 = new javax.swing.JRadioButton();
        rbtn_Curso2 = new javax.swing.JRadioButton();
        rbtn_Curso3 = new javax.swing.JRadioButton();
        rbtn_Curso4 = new javax.swing.JRadioButton();
        rbtn_Curso5 = new javax.swing.JRadioButton();
        jSeparator2 = new javax.swing.JSeparator();
        txt_Curso1 = new javax.swing.JTextField();
        txt_Curso2 = new javax.swing.JTextField();
        txt_Curso3 = new javax.swing.JTextField();
        txt_Curso4 = new javax.swing.JTextField();
        txt_Curso5 = new javax.swing.JTextField();
        btn_Guardar = new javax.swing.JButton();
        btn_volver = new javax.swing.JButton();
        btn_Rehacer = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Swis721 WGL4 BT", 1, 28)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setText("INSCRIPCIÓN DE ASIGNATURAS");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 470, 50));

        jLabel5.setFont(new java.awt.Font("Tekton Pro Ext", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setText("CURSOS DISPONIBLES");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, 20));

        jLabel7.setFont(new java.awt.Font("Tekton Pro Ext", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 0));
        jLabel7.setText("CRÉDITOS");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 110, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/132womanstudent2_100407 (1).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 90, 220, 260));

        rbtn_Curso1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_Curso1ActionPerformed(evt);
            }
        });
        getContentPane().add(rbtn_Curso1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 150, -1));

        rbtn_Curso2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_Curso2ActionPerformed(evt);
            }
        });
        getContentPane().add(rbtn_Curso2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 150, -1));

        rbtn_Curso3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_Curso3ActionPerformed(evt);
            }
        });
        getContentPane().add(rbtn_Curso3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 150, -1));

        rbtn_Curso4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_Curso4ActionPerformed(evt);
            }
        });
        getContentPane().add(rbtn_Curso4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 150, -1));

        rbtn_Curso5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_Curso5ActionPerformed(evt);
            }
        });
        getContentPane().add(rbtn_Curso5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 150, -1));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 10, 280));

        txt_Curso1.setEditable(false);
        getContentPane().add(txt_Curso1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, 60, -1));

        txt_Curso2.setEditable(false);
        getContentPane().add(txt_Curso2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, 60, -1));

        txt_Curso3.setEditable(false);
        getContentPane().add(txt_Curso3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 60, -1));

        txt_Curso4.setEditable(false);
        getContentPane().add(txt_Curso4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 60, -1));

        txt_Curso5.setEditable(false);
        getContentPane().add(txt_Curso5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, 60, -1));

        btn_Guardar.setText("GUARDAR");
        btn_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 100, 50));

        btn_volver.setText("VOLVER");
        btn_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_volverActionPerformed(evt);
            }
        });
        getContentPane().add(btn_volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 110, 50));

        btn_Rehacer.setText("REHACER");
        btn_Rehacer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RehacerActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Rehacer, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 100, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo_1.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    

    private void btn_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GuardarActionPerformed

        JOptionPane.showMessageDialog(null,"Se ha guardado correctamente");
    }//GEN-LAST:event_btn_GuardarActionPerformed

    private void btn_RehacerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RehacerActionPerformed
        dispose();
        InscripcionCursos mc = new InscripcionCursos();
        mc.setVisible(true);

    }//GEN-LAST:event_btn_RehacerActionPerformed

    private void btn_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_volverActionPerformed
        Inicio inicio= new Inicio();
        inicio.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_volverActionPerformed

    private void rbtn_Curso1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_Curso1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn_Curso1ActionPerformed

    private void rbtn_Curso2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_Curso2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn_Curso2ActionPerformed

    private void rbtn_Curso3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_Curso3ActionPerformed

    }//GEN-LAST:event_rbtn_Curso3ActionPerformed

    private void rbtn_Curso4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_Curso4ActionPerformed

    }//GEN-LAST:event_rbtn_Curso4ActionPerformed

    private void rbtn_Curso5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_Curso5ActionPerformed

    }//GEN-LAST:event_rbtn_Curso5ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Guardar;
    private javax.swing.JButton btn_Rehacer;
    private javax.swing.JButton btn_volver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JRadioButton rbtn_Curso1;
    private javax.swing.JRadioButton rbtn_Curso2;
    private javax.swing.JRadioButton rbtn_Curso3;
    private javax.swing.JRadioButton rbtn_Curso4;
    private javax.swing.JRadioButton rbtn_Curso5;
    private javax.swing.JTextField txt_Curso1;
    private javax.swing.JTextField txt_Curso2;
    private javax.swing.JTextField txt_Curso3;
    private javax.swing.JTextField txt_Curso4;
    private javax.swing.JTextField txt_Curso5;
    // End of variables declaration//GEN-END:variables
}
