
package Vista;

import Vista.Login;
import Vista.Inicio;
import javax.swing.JOptionPane;
import java.text.DateFormat;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import proyectomelanie.Estudiante;

public class Registrarse extends javax.swing.JFrame {

    private Estudiante estudiante=new Estudiante();//objeto estudiante
    

    public Estudiante getEstudiante() {
        return estudiante;
    }

    public void setEstudiante(Estudiante estudiante) {
        this.estudiante = estudiante;
    }
    
    
    public Registrarse() {
        initComponents(); //PARA QUE SIRVE ESTO???
        this.setLocationRelativeTo(null);

    }


     /* This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_Titulo = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        txt_apellidos = new javax.swing.JTextField();
        txt_código = new javax.swing.JTextField();
        opc_Sexo = new javax.swing.JComboBox<>();
        txt_direccion = new javax.swing.JTextField();
        txt_telefono = new javax.swing.JTextField();
        txt_Alumno = new javax.swing.JLabel();
        txt_Padres = new javax.swing.JLabel();
        txt_nombreP = new javax.swing.JTextField();
        txt_apellidosP = new javax.swing.JTextField();
        opc_sexoP = new javax.swing.JComboBox<>();
        
        txt_TelefonoP = new javax.swing.JTextField();
        btn_Guardar = new javax.swing.JButton();
        btn_Volver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_contraseña = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jSeparator1 = new javax.swing.JSeparator();
        fondo = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_Titulo.setFont(new java.awt.Font("Viner Hand ITC", 1, 24)); // NOI18N
        txt_Titulo.setForeground(new java.awt.Color(255, 51, 0));
        txt_Titulo.setText("DATOS GENERALES");
        getContentPane().add(txt_Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 290, 30));

        txt_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreActionPerformed(evt);
            }
        });
        txt_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nombreKeyTyped(evt);
            }
        });
        getContentPane().add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 78, 130, -1));

        txt_apellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_apellidosActionPerformed(evt);
            }
        });
        txt_apellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_apellidosKeyTyped(evt);
            }
        });
        getContentPane().add(txt_apellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 130, -1));

        txt_código.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_códigoKeyTyped(evt);
            }
        });
        getContentPane().add(txt_código, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 110, -1));

        opc_Sexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "F", "M" }));
        getContentPane().add(opc_Sexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, -1));

        txt_direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_direccionActionPerformed(evt);
            }
        });
        getContentPane().add(txt_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 110, -1));

        txt_telefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_telefonoKeyTyped(evt);
            }
        });
        getContentPane().add(txt_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 100, -1));

        txt_Alumno.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        txt_Alumno.setForeground(new java.awt.Color(153, 0, 0));
        txt_Alumno.setText("DATOS DEL ALUMNO");
        getContentPane().add(txt_Alumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        txt_Padres.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        txt_Padres.setForeground(new java.awt.Color(153, 0, 0));
        txt_Padres.setText("DATOS DEL PADRE/APODERADO");
        getContentPane().add(txt_Padres, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 260, -1));

        txt_nombreP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombrePActionPerformed(evt);
            }
        });
        txt_nombreP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nombrePKeyTyped(evt);
            }
        });
        getContentPane().add(txt_nombreP, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 110, -1));

        txt_apellidosP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_apellidosPActionPerformed(evt);
            }
        });
        txt_apellidosP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_apellidosPKeyTyped(evt);
            }
        });
        getContentPane().add(txt_apellidosP, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 110, -1));

        opc_sexoP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "F", "M" }));
        getContentPane().add(opc_sexoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, -1, -1));

        

        txt_TelefonoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_TelefonoPActionPerformed(evt);
            }
        });
        txt_TelefonoP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_TelefonoPKeyTyped(evt);
            }
        });
        getContentPane().add(txt_TelefonoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, 90, -1));

        btn_Guardar.setText("GUARDAR");
        btn_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, 90, 40));

        btn_Volver.setText("VOLVER");
        btn_Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_VolverActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, 90, 40));

        jLabel1.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Nombres:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("Apellidos:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setText("Código:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 102));
        jLabel4.setText("Sexo:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jLabel5.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 102));
        jLabel5.setText("F.Nacimiento:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        jLabel6.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 102));
        jLabel6.setText("Dirección:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        jLabel7.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 102));
        jLabel7.setText("Teléfono:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        jLabel8.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 102));
        jLabel8.setText("Nombres:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, -1, -1));

        jLabel9.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 102));
        jLabel9.setText("Apellidos:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, -1, -1));

        jLabel10.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 102));
        jLabel10.setText("Sexo:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, -1, -1));

        

        jLabel12.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 102));
        jLabel12.setText("Teléfono:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, -1, -1));

        jLabel13.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 102));
        jLabel13.setText("Contraseña:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));
        getContentPane().add(txt_contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 160, -1));
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 160, -1));

       

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 10, 320));

        fondo.setFocusable(false);
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 440));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo2.jpg"))); // NOI18N
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreActionPerformed

    private void txt_nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nombreKeyTyped

        char _ch = evt.getKeyChar();
        if(!Character.isLetter(_ch))evt.consume();
    }//GEN-LAST:event_txt_nombreKeyTyped

    private void txt_apellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_apellidosActionPerformed
        
    }//GEN-LAST:event_txt_apellidosActionPerformed

    private void txt_códigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_códigoKeyTyped

        char _ch = evt.getKeyChar();
        if(!Character.isDigit(_ch))evt.consume();
    }//GEN-LAST:event_txt_códigoKeyTyped

    private void txt_direccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_direccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_direccionActionPerformed

    private void txt_telefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_telefonoKeyTyped
        char _ch = evt.getKeyChar();
        if(!Character.isDigit(_ch))evt.consume();
    }//GEN-LAST:event_txt_telefonoKeyTyped

    private void btn_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GuardarActionPerformed
       
       if(!txt_Alumno.getText().equals("")&& !txt_Padres.getText().equals("") 
              &&!txt_TelefonoP.getText().equals("")&& !txt_apellidos.getText().equals("")
              && !txt_apellidosP.getText().equals("")&&!txt_contraseña.getText().equals("")
              && !txt_código.getText().equals("") && !txt_direccion.getText().equals("")
              && !txt_nombreP.getText().equals("") && !txt_nombre.getText().equals("")
              && !txt_telefono.getText().equals("")    ){
            Login registrarse2=new Login();
            registrarse2.getEstudiante().setNombres(txt_nombre.getText());
            registrarse2.getEstudiante().setApellidos(txt_apellidos.getText());
            registrarse2.getEstudiante().setCodigo(txt_código.getText());
            registrarse2.getEstudiante().setSexo(opc_Sexo.getItemAt(opc_Sexo.getSelectedIndex()).charAt(0));
            Date fecha = jDateChooser1.getDate();
            String strFecha = DateFormat.getDateInstance().format(fecha);
            registrarse2.getEstudiante().setFechaNacimiento(strFecha);
            registrarse2.getEstudiante().setDirección(txt_direccion.getText());
            registrarse2.getEstudiante().setTelefono(txt_telefono.getText());
            registrarse2.getEstudiante().setContraseña(txt_contraseña.getText());
            registrarse2.getEstudiante().getPadre().setNombres(txt_nombreP.getText());
            registrarse2.getEstudiante().getPadre().setApellidos(txt_apellidosP.getText());
            registrarse2.getEstudiante().getPadre().setSexo(opc_sexoP.getItemAt(opc_sexoP.getSelectedIndex()).charAt(0));
            registrarse2.getEstudiante().getPadre().setTelefono(txt_TelefonoP.getText());
    
            registrarse2.setVisible(true);

            dispose();
       }
       else JOptionPane.showMessageDialog(null, "Complete los datos!");
        
    }//GEN-LAST:event_btn_GuardarActionPerformed

    private void txt_apellidosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_apellidosKeyTyped
       
       char _ch = evt.getKeyChar();
        if(!Character.isLetter(_ch))evt.consume();

    }//GEN-LAST:event_txt_apellidosKeyTyped

    private void txt_nombrePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombrePActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombrePActionPerformed

    private void txt_nombrePKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nombrePKeyTyped
       
        char _ch = evt.getKeyChar();
        if(!Character.isLetter(_ch))evt.consume();
    }//GEN-LAST:event_txt_nombrePKeyTyped

    private void txt_apellidosPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_apellidosPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_apellidosPActionPerformed

    private void txt_apellidosPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_apellidosPKeyTyped
        
        char _ch = evt.getKeyChar();
        if(!Character.isLetter(_ch))evt.consume();
    }//GEN-LAST:event_txt_apellidosPKeyTyped

    private void txt_TelefonoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_TelefonoPActionPerformed
     
        
    }//GEN-LAST:event_txt_TelefonoPActionPerformed

    private void txt_TelefonoPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_TelefonoPKeyTyped
        char _ch = evt.getKeyChar();
        if(!Character.isDigit(_ch))evt.consume(); }//GEN-LAST:event_txt_TelefonoPKeyTyped

    private void btn_VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_VolverActionPerformed
        Inicio Inicio=new Inicio();
        Inicio.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_VolverActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Guardar;
    private javax.swing.JButton btn_Volver;
    private javax.swing.JLabel fondo;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<String> opc_Sexo;
    private javax.swing.JComboBox<String> opc_sexoP;
    private javax.swing.JLabel txt_Alumno;
    private javax.swing.JLabel txt_Padres;
    private javax.swing.JTextField txt_TelefonoP;
    private javax.swing.JLabel txt_Titulo;
    private javax.swing.JTextField txt_apellidos;
    private javax.swing.JTextField txt_apellidosP;
    private javax.swing.JTextField txt_código;
    private javax.swing.JTextField txt_direccion;
    private javax.swing.JTextField txt_contraseña;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_nombreP;
    private javax.swing.JTextField txt_telefono;
    // End of variables declaration//GEN-END:variables
}
