package proyecto_matricula;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */




import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import proyecto_matricula.Alumno;
import proyecto_matricula.Facultad;
import proyecto_matricula.Formulario;
import proyecto_matricula.Login;
import proyecto_matricula.Profesion;



/**
 *
 * @author Lenovo
 */
public final class EscuelaGeneral extends javax.swing.JFrame {

    /**
     * Creates new form EscuelaGeneral
     */
     
  

    DefaultComboBoxModel modeloProfesion;
    DefaultComboBoxModel modeloFacultad ;
    DefaultComboBoxModel modeloSeries ;
    

    Facultad facu = new Facultad();
    Profesion prof_1 = new Profesion();
    Profesion prof_2 = new Profesion();

    
    String facultad,profesion,semestre;
     
    public EscuelaGeneral() {
        initComponents();
        this.setLocationRelativeTo(null);
       Facultades();
       Serie();  
       
     
        
        
      }
        
    public final void Facultades(){
        
       
       ArrayList<String> nomFacultades = new ArrayList<>();
       nomFacultades.add("Facultad de Ciencias e Ingeniería");
       nomFacultades.add("Facultad de Arte y Diseño");
       facu.setNomFacultades(nomFacultades);
       
       String [] numFacu = new String[facu.getNomFacultades().size()]; 
       for(int i=0;i<facu.getNomFacultades().size();i++){
           String it = facu.getNomFacultades().get(i);
           numFacu[i] = it;
           
           
           
       }
        modeloFacultad = new DefaultComboBoxModel(numFacu);
        cmb_facultad.setModel(modeloFacultad);
        
    }
    
    
    public final void Profesion(){
        
        ArrayList<String> nomProfesiones_1 = new ArrayList<>();
        
        nomProfesiones_1.add("Ingeniería Mecátrónica");
        nomProfesiones_1.add("Ingeniería Geológica");
        nomProfesiones_1.add("Ingenieria Civil");
        prof_1.setNomProfesiones(nomProfesiones_1);
        
        ArrayList<String> nomProfesiones_2 = new ArrayList<>();
        nomProfesiones_2.add("Diseño Gráfico");
        nomProfesiones_2.add("Diseño Industrial");
        nomProfesiones_2.add("Arte, moda y diseño textil");
        prof_2.setNomProfesiones(nomProfesiones_2);
        
        
        //***********************************************************
       
        String[] fac_1= new String [prof_1.getNomProfesiones().size()];
        
        for(int i=0;i<prof_1.getNomProfesiones().size();i++){
           String it = prof_1.getNomProfesiones().get(i);
           fac_1[i] = it;
                               
        }
        
        String[] fac_2= new String [prof_2.getNomProfesiones().size()];
        
        for(int i=0;i<prof_2.getNomProfesiones().size();i++){
           String iti = prof_2.getNomProfesiones().get(i);
           fac_2[i] = iti;
                               
        }
        
        
          //*********************
        
        String profesiones = cmb_facultad.getSelectedItem().toString();
        
         if(profesiones.equals("Facultad de Ciencias e Ingeniería")){
           modeloProfesion = new DefaultComboBoxModel(fac_1);
          
        }else if(profesiones.equals("Facultad de Arte y Diseño")){
            modeloProfesion = new DefaultComboBoxModel(fac_2);
           
        }
            cmb_carrera.setModel(modeloProfesion);
    
        
       
          
        
        
    }
    
    public void Serie(){
        String [] series = {"100-1","100-2"};
        modeloSeries = new DefaultComboBoxModel(series);
        cmb_Serie.setModel(modeloSeries);
                
    }
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cmb_facultad = new javax.swing.JComboBox<String>();
        cmb_carrera = new javax.swing.JComboBox<String>();
        jLabel6 = new javax.swing.JLabel();
        cmb_Serie = new javax.swing.JComboBox<String>();
        btn_guardar = new javax.swing.JButton();
        btn_volver = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Bauhaus 93", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 255, 51));
        jLabel2.setText("DATOS ESPECÍFICOS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 480, 60));

        jLabel7.setFont(new java.awt.Font("Tekton Pro", 1, 24)); // NOI18N
        jLabel7.setText("Facultad:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, 40));

        jLabel1.setFont(new java.awt.Font("Tekton Pro", 1, 24)); // NOI18N
        jLabel1.setText("Profesión:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        cmb_facultad.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_facultadItemStateChanged(evt);
            }
        });
        cmb_facultad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_facultadActionPerformed(evt);
            }
        });
        getContentPane().add(cmb_facultad, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 340, 30));

        cmb_carrera.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_carreraItemStateChanged(evt);
            }
        });
        getContentPane().add(cmb_carrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 340, 30));

        jLabel6.setFont(new java.awt.Font("Tekton Pro", 1, 24)); // NOI18N
        jLabel6.setText("Serie:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, -1, -1));

        cmb_Serie.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        cmb_Serie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_SerieActionPerformed(evt);
            }
        });
        getContentPane().add(cmb_Serie, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 80, 30));

        btn_guardar.setText("ACEPTAR");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, 110, 50));

        btn_volver.setText("VOLVER");
        btn_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_volverActionPerformed(evt);
            }
        });
        getContentPane().add(btn_volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 420, 120, 50));

        fondo.setFont(new java.awt.Font("Tekton Pro", 1, 24)); // NOI18N
        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesFrame/login_1.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmb_facultadItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_facultadItemStateChanged
    
    }//GEN-LAST:event_cmb_facultadItemStateChanged

    
    
    
    private void cmb_facultadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_facultadActionPerformed
       Profesion();
    }//GEN-LAST:event_cmb_facultadActionPerformed

    private void cmb_carreraItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_carreraItemStateChanged
       
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_carreraItemStateChanged

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
      
        
        if(cmb_facultad.getItemCount()>=0&&cmb_facultad.getItemCount()<3){
            facultad=String.valueOf(cmb_facultad.getSelectedItem());
        }
       
        if(cmb_carrera.getItemCount()>=0&&cmb_carrera.getItemCount()<4){
            profesion=String.valueOf(cmb_carrera.getSelectedItem());
        }
        
        if(cmb_Serie.getItemCount()>=0&&cmb_Serie.getItemCount()<3){
            semestre=String.valueOf(cmb_Serie.getSelectedItem());
        }
        
        
        Alumno n1 = new Alumno(facultad, profesion, semestre);
        System.out.println("\n\tDATOS GENERALES DEL ALUMNO");
        System.out.println(n1.mostrarDatosGenerales());
        
//        if(cmb_facultad.getSelectedIndex()==0&&cmb_carrera.getSelectedIndex()==0&&cmb_Serie.getSelectedIndex()==0){
//               
//        InscripcionCursos ne = new InscripcionCursos(1);
//        
//                
//       }
        
        
        
        
        
        
       Login login =new Login();
       login.setVisible(true);
       dispose();

    }//GEN-LAST:event_btn_guardarActionPerformed

    private void btn_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_volverActionPerformed
        Formulario escuela=new Formulario();
        escuela.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_volverActionPerformed

    private void cmb_SerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_SerieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_SerieActionPerformed

    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_volver;
    private javax.swing.JComboBox<String> cmb_Serie;
    private javax.swing.JComboBox<String> cmb_carrera;
    private javax.swing.JComboBox<String> cmb_facultad;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
